config/routes.rb
Yatl::Application.routes.draw do
  root :to=>"home#index"
  resources :buckets
end

app/models/bucket.rb
class Bucket < ActiveRecord::Base
  has_many :items
  validates_presence_of :name
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :bucket
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  def index
    @buckets = Bucket.all
  end
  def create
    @bucket = Bucket.new(params[:bucket])
    if(@bucket.save)
      redirect_to @bucket, :notice=>"created successfully"
    else
      render :action=>:new
    end
  end
  def new
    @bucket = Bucket.new
  end
  def edit
    @bucket = Bucket.find(params[:id])
  end
  def update
    @bucket = Bucket.find(params[:id])
    if(@bucket.update_attributes(params[:bucket]))
      redirect_to @bucket, :notice=>"Updated successfully"
    else
      render :action=>:edit
    end
  end
  def show
    @bucket = Bucket.find(params[:id])
  end
  def destroy
    @bucket = Bucket.find(params[:id])
    @bucket.destroy
    redirect_to buckets_path, :notice=>"Deleted successfully"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/buckets/_bucket.html.erb
<div class="bucket">
  <%=link_to bucket.name, bucket %>
  <%=link_to 'Edit', edit_bucket_path(bucket) %>
  <%=link_to 'Delete',bucket, :method=>"delete", :confirm=>"Are you sure you want to delete this?" %>
</div>

app/views/buckets/_form.html.erb
<%= semantic_form_for @bucket do |f| %>
  <%= f.inputs %>
  <%= f.buttons %>
<% end %>

app/views/buckets/edit.html.erb
<h1>Editing Bucket</h1>
<%=render :partial=>"form" %>

app/views/buckets/index.html.erb
<h1>Listing buckets</h1>
<div class="buckets">
  <%= render @buckets %>
</div>
<%=link_to "New Bucket", new_bucket_path %>

app/views/buckets/new.html.erb
<h1>Create a new bucket</h1>
<%=render :partial=>"form" %>

app/views/buckets/show.html.erb
<h1>Showing Bucket</h1>
<%=render @bucket%>

app/views/home/index.html.erb
<h1>Hello world</h1>
<p>Time now is <%=Time.now%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yatl</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%=notice%></p>
<p class="alert"><%=alert%></p>
<%= yield %>

</body>
</html>